### ISSUE TITLE
generating a new route with all its parts (default css, e2e-spec.ts, html-tpl,spec.ts,tns, ts,..)

### ISSUE THREAD

**Issue by nxpatterns** [NathanWalker/angular-seed-advanced#128]
Is that possible with "one-click" within an ide or via a generator? How can I overcome that simplest?

thank you

**Comment by joshwiens** [comment]
Fastest way to do what you want to do would be with the angular-cli once it's in a usable state.
Nobody is creating generators for the above because it would be replaced by the CLI at some point.

This is what you are going to want at some point in the future - https://github.com/angular/angular-cli
