### ISSUE TITLE
Workflow for mobile development

### ISSUE THREAD

**Issue by aaweb** [NathanWalker/angular-seed-advanced#15]
Hello there

First of all, thanks for this amazing project. I trying to find the best way to develop on iOS using the simulator. 

I can run the app using:
`npm run start.ios`

However, live sync does not seem to work. I also tried running the following from the nativescript folder:
`tns livesync ios --emulator --watch`

After the usual typescript errors, it says "Compilation complete. Watching for file changes", but never updates when I change a file.

Am I missing something obvious here? Cheers

**Comment by NathanWalker** [comment]
@aaweb You're welcome, hope it's working out for you.

There's 2 things to keep in mind here.
1. `npm run start.ios` actually copies contents of `src` directory into `nativescript` folder. Given this, when you make changes in `src`, `livesync` would not see them since `livesync` would only be watching the `nativescript` folder. We would need another `watch` task that would pick up changes in `src`, then copy the contents again to `nativescript` folder which would trigger `livesync`.
2. I'm aware of some issues with `livesync` which is why I'm not using it in the `npm run start.ios` task.
Once I hear it is solid, I will update the task here. If you have particular questions about `tns livesync`, you may want to post that question here (check out open issues around it at the moment): 
https://github.com/NativeScript/nativescript-cli/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+livesync

I'm hoping to find a solution that would allow `livesync` to work with NativeScript here so stay tuned but in meantime, `npm run start.ios` after making changes in `src` each time.

Let me know if you find any interesting workarounds to get `livesync` to work.

**Comment by aaweb** [comment]
In another project I worked around it by adding a file in the `before-watch` folder which creates a symbolic link:

```
var path = require('path');
var shelljs = require('shelljs');

module.exports = function() {
    shelljs.ln('-sf', '../src/frameworks', 'app/frameworks');
}
```

Not sure what other implications that would have, but in your case removing spec files and such wouldn't work as done in 'npm prepare'. 

Any example or advice on where and how to best add a watcher for that? That's my number one "annoyance" right now :) Thanks again for the great project. Love the ongoing progress!

**Comment by aaweb** [comment]
Hm... I tried manually changing a component's html file under `src/nativescript/app/components` to try to see if I can "simulate" what a watch task should do. However, nothing is triggered if I change it there. It is triggered however when I change it in `src/client/app/components`.

Where would I need to hook into for that?

I'd really like to figure this out as iOS development like this is no joy :(
