### ISSUE TITLE
Issue with font/image relative paths in css and Electron

### ISSUE THREAD

**Issue by fourctv** [NathanWalker/angular-seed-advanced#158]
I have some icons that load via 'styles' embedded into one of my components. They are all declared like this in a .css file:

```
.quickFinder-refresh-icon {
  background-image: url('assets/icons/refreshIcon.png');
 }
```

That works fine on the web, but when I try it via `start.desktop` those icons fail to load.

On debugger I can see that Electron tries to load them as `file:///assets/...`, and of course they are not there.
I've tried to change the url to `/assets/icons/refreshIcon.png` or `./assets/icons/refreshIcon.png`. I've also tried to have a `<img>` element to load the icon but I get the same result in Electron.

Weird is that I have similar image elements in other components that load fine.
The problem seems to be in the image path resolution. Somehow Electron fails to resolve resource element's path from deep inside the component tree.

Any help in trying to solve this will be appreciated.

TIA
julio

**Comment by fourctv** [comment]
I did a lot of testing in trying to sort out path resolution in Electron, but I could not figure out how to get to my `assets/icons` folder, from a component's `.css`.

As a workaround for now, I moved all my icon style classes to `main.css` and the `icons` folder into `client/css`, and now they load fine.

My icon style declarations in `main.css` now look like:

```
.quickFinder-refresh-icon {
    background-image: url("./icons/refreshIcon.png");
}
```

I'd love to be able to move that to my component's css...

I hope someone comes up with a way to do that :-)

**Comment by YounessElLamzi** [comment]
I got exactly the same issue & indeed for now I had to do the same workaround... :) 
Still trying to figure out how to fix this. 

It would be nice if there would be a solution for this.

**Comment by Kaffiend** [comment]
for the fonts, refer to the parent seed addition of external fonts. The issue is the fonts are not carried over into the dist directory by the gulp task, you will have to had a new dependent task to handled external fonts, like the parent seed. for reference here is what is carried over into the dist directory on a desktop build. For a quick fix though just for dekstop you could add `node_modules/font-awesome/**/*` to [this array](https://github.com/NathanWalker/angular-seed-advanced/blob/master/tools/tasks/project/desktop.libs.ts#L8) and it will bring them over for the electron. 

When you use the assets directory are the image/icons actually copied over to the dist directory?
If they are not, then you may need to make a dependent gulp task like fonts to copy over assets to the dist directory. Ill look more into this later this evening.

**Comment by NathanWalker** [comment]
@Kaffiend's suggestion works, thanks 👍
