### ISSUE TITLE
HTTP Not working in NativeScript

### ISSUE THREAD

**Issue by zeeshanjan82** [NathanWalker/angular-seed-advanced#185]
I am working on angular2 + nativescript project using this seed project and I am not able to make a simple HTTP POST call using this code

``` js
    return this.http.post(`${AppConfigService.API_PATH}/login`, body, options)
              .map(res => res.json())
              .catch((err: any) => {
                return Observable.throw(err);
              });
```

this code works fine in normal angular2 app but in native script it gives the error:
Response with status: 200 for URL: null

**Comment by NathanWalker** [comment]
Hi @zeeshanjan82 are you working off the latest master from this seed?

Lemme know if you have `HttpService` in your codebase (previously the seed provided that service as an intermediate to bridge to next version of {N}), it was recently removed as was no longer needed.

Also please check that your `nativescript/package.json` should ref at least these 2:

```
"nativescript-angular": "next",
"tns-core-modules": "next",
```

Lastly, ensure that your `NS_APP_PROVIDERS` should be using `NS_HTTP_PROVIDERS` here:
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/nativescript/app/shared/nativescript/index.ts#L21

However sounds like your issue may be due to your api being unreachable due to invalid ip used from device or emulator: https://github.com/NativeScript/NativeScript/issues/2536#issuecomment-236407132

**Comment by zeeshanjan82** [comment]
thanks @NathanWalker the issue was mainly because I was calling an https service which has not valid SSL certificate though I was not able to make out this error easily, but I am closing this issue.

**Comment by AlexMesser** [comment]
Just faced same issue. If you are tying to connect to localhost address in your emulator then make sure you are accessing `http://10.0.2.2/api` instead of `http://localhost/api`

**Comment by oliveiracdz** [comment]
For GenyMotion emulator the loopback address is `http://10.0.3.2/api`:
https://stackoverflow.com/a/39958955/1440095

**Comment by Irvinhoe** [comment]
I dont think this issue was resolved fully. Can someone explain why apiUrl = "http://192.168.1.100:8080/myapp/api" does not work in nativescript?? Even after including appropriate headers.  

  login(user: User) {

    let headers = new Headers();
    headers.append("Accept", "application/json");
    headers.append("Content-Type", "application/json");

    return this.http.post(
      Config.apiUrl + "users/token",
      JSON.stringify({
        username: user.phone_no,
        password: user.pin_code
  
      }),
      { headers: headers }
    )
    .map(response => response.json())
    .do(data => {
      Config.token = data.Result.access_token;
    })
    .catch(this.handleErrors);
  }

**Comment by jogboms** [comment]
@Irvinhoe does `http://192.168.1.100:8080/myapp/api` point to an address on an actual server or on your local machine?

Secondly, are you testing out your app via an emulator or an actual device?

**Comment by Irvinhoe** [comment]
@jogboms The address point to a local pc. Testing on emulator and actual device.

**Comment by jogboms** [comment]
```ts
import { isAndroid, device } from "tns-core-modules/platform/platform";

function isEmulator() {
	if (device.model.includes("google_sdk") || device.model.includes("Emulator")) {
		return true;
	}
	return false;
}
const localnetwork = "192.168.8.54";
const localhost = isAndroid ? (isEmulator() ? "10.0.2.2" : localnetwork) : "localhost";
```

@Irvinhoe that's the way i do it. where `localnetwork` is the IP of the machine where machine and phone is connected to the same network.

[More info](https://futurestud.io/tutorials/how-to-run-an-android-app-against-a-localhost-api)
