### ISSUE TITLE
NPM_DEPENDENCIES vs APP_ASSETS, and how to include dependencies in general

### ISSUE THREAD

**Issue by syrys** [NathanWalker/angular-seed-advanced#192]
Hey Guys,

This is a help/advice/question, and probably benefit being documented somewhere (maybe as inline comments on the `project.config.ts`).

I had a look at the `project.config.ts`, and found it a little vague and confusing. Well, it has 2 sections for `APP_ASSETS` and `NPM_DEPENDENCIES`, then each of those has options like `inject: 'libs'`, `inject: true`, `vendor: false`. For starters, i dont really understand what all the options are and what each of the options mean. Secondly, what exactly is the difference between `NPM_DEPENDENCIES` array and the `APP_ASSETS` array.

So, lets define some use cases. How would i go about them:
1. I want to add a JS library to the frontend (web/view). Lets say ng2 bootstrap?
2. What if the library came with dependencies, how do i attach them (ie bootstrap's main js file is required by ng2 bootstrap)?
3. What if the library (or its dependencies) came with css files, how do i attach them (ie bootstrap's css file)?
4. What if the library was not pulled from npm. What if it was a JS file or couple of js files pulled off from another project, where would i save them and how would i attach/include them? (for frontend use)
5. How would i add a js library for backend/electron? (lets say `socket.io` as an example downloaded from `npm install`).
6. How would i add a JS library/files to backend/electron that were NOT pulled from npm. ie. some files/classes written for another project form example. Where would i save them and how would i include/use them?

PS. im sure i can figure them out on my own, i sort of have already anyway. But its good to know the official/proper way to do it incase im hacking it and not doing how things should be done. Also its good to have it documented.

Cheers,
TY in advance.

**Comment by NathanWalker** [comment]
Hi @syrys a lot of questions like these can be answered in parent seed wiki here:
https://github.com/mgechev/angular2-seed/wiki
https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency

I would recommend studying the wiki there as this seed is merely an expansion of it's parent.

As far as electron, the electron implementation here is very much experimental and intended to generate community discussion around best ways to integrate. As such, it is open to interpretation as well as improvement via Pull Request.

The parent seed has done a good job of answering the majority of your questions above so I will close this, however in regards to electron, I am planning to provide a single example of what all files need modification when integrating an example library and that will be addressed via this issue here: https://github.com/NathanWalker/angular2-seed-advanced/issues/176

**Comment by syrys** [comment]
@NathanWalker Alright, Thanks, that should give me enough info to figure things out. Could we probably add a section in the readme file or this repo's wiki that links people to corresponding repo's wiki's for specific sections (ie. base -> go here, electron -> go here, gulp -> go here, nativescript -> go here)? 

Main problem for me is, i came here not knowing much about the angular2-seed (and im new to angular2 as well), and i see that this repo has not much documentation for noobs, but since this is an extension of a lot of repo's, its hard for me to tell where one repo starts and the other repo begins (specially as you said, with electron integration and all that). Therefore, makes it a bit hard to know where to look for info (if its unique to this repo or related to another repo).

**Comment by kbrandwijk** [comment]
Any news on how to get dependencies added into the electron version? Right now, I can only get it to work when npm installing to both root and src/client, but that's a lot of overhead with multiple libraries.

**Comment by kbrandwijk** [comment]
Found out the missing piece of information in another issue. Adding the node_modules to desktop.libs.ts did the trick. Why is it necessary to specify this manually? It seems adding them to project.config.js should automagically include them into the desktop.libs step?

I mean, can't the desktop.libs task copy based on the dependency list, instead of manually specifying a list again there? As this is a closed issue, I'll open a new one for it.
