### ISSUE TITLE
Changed pages are not reloaded in Chrome, Canary or Firefox

### ISSUE THREAD

**Issue by st-clair-clarke** [NathanWalker/angular-seed-advanced#20]
Hi Nathan,
After changing a .ts, .html, etc, source in  the advanced-seed project, I see the gulp task print the 'Reloading page...' in the console, but the page does not actually reload.

I think the problem lies with the seed dependency on LiveReload. I installed LiveReload 2.1.0, but clicking the icon in the browser attempting to enable it always result in 

'Could not connect to LiveReload server. Please make sure that a compatible LiveReload server is running.'

Did you experience this in your test, and how did you overcome it? I see a lot of similar issues on the web about the compatibility of livereload. It is an issue for me now because currently I have to always do an 'npm start' to see my work-change and this does consume a lot of time. 

Please let me know if you have an alternative to reload the pages.

Great seed Nathan. And thanks.

**Comment by NathanWalker** [comment]
Hi @st-clair-clarke, thanks for the report. I'm seeing reloads work just fine in Chrome `Version 49.0.2623.108 (64-bit)`, and Firefox `45.0.1`.

You shouldn't need 'LiveReload' extension in your browser as it's handled all through the seed and BrowserSync. That may be your issue, may need to uninstall that extension or disable it with the seed.

Additionally, the advanced seed here mirrors the build setup in it's parent https://github.com/mgechev/angular2-seed, so anything `build` related, you may want to post there. However, it appears everything with live reloading is working correctly.

After trying the above extension uninstall, please report back if it fixes for you. Otherwise, maybe post on the parent seed. Thanks and good luck!

**Comment by st-clair-clarke** [comment]
You were correct Nathan. After uninstalling LiveReload, everything now work as expected. Thanks again.
