### ISSUE TITLE
Question: How to use platform specific components/directives.

### ISSUE THREAD

**Issue by m-abs** [NathanWalker/angular-seed-advanced#202]
Hi,

I tried asking this on twitter but the 140-character limit made it unclear, so I'll try here.

In `angular2-seed-advanced`, I'd like to be able to load a component/directive only on {N} and not on web. Is this possible? And if yes, how? :) 

Explanation:
In our project we have two versions of a component, one is for web and the other is for {N}.

As I understand it, DI doesn't work on the `@Component` decorator parameters, at least I couldn't get it to work by providing the component in `src/client/main.web.ts` or `nativescript/app/app.ts`.

So I've solved it temporarily by creating the files `src/client/platform.ts` and `nativescript/app/platform.ts` which exports the component for each platform. _(This isn't pretty but it's  okay because we only need to use the component on a single page.)_

But now I need to load a directive for {N}-only and on all pages and I would prefer a better solution than that.

**Comment by NathanWalker** [comment]
Hi @m-abs there are certainly cases where you will need to do this. Honestly your solution is not bad and I've done the same thing myself in similar cases.
You can certainly create custom components/directives for either platform in:
- `src/client` (web), platform only can go here: https://github.com/NathanWalker/angular2-seed-advanced/tree/master/src/client (just create a new folder to house web only components/directives - note: don't put the new folder in `app` folder there since that is shared with {N} app)
- `nativescript/app` ({N}), platform only can go here: https://github.com/NathanWalker/angular2-seed-advanced/tree/master/nativescript/app/shared  (that folder is not shared with the web)

In both cases, you would import those in the bootstrap file for use throughout that specific platform.

You could also create a shared `APP_PLATFORM_COMPONENTS` array which would be filled per platform in each respective bootstrap file. That array would be filled with the platform specific components/directives in each respective platform.

However the ideal solution here will likely be to use the new `NgModule` with rc.5 once this branch gets merged: https://github.com/NathanWalker/angular2-seed-advanced/tree/rc5-upgrade 👍

**Comment by kbrandwijk** [comment]
Any updates on this platform-specific component approach now rc5 is here?

**Comment by m-abs** [comment]
We haven't gotten to it yet, but we'll go with NgModule to do it.
