### ISSUE TITLE
templateUrl and styleUrls - wrong linkage breaks production build

### ISSUE THREAD

**Issue by red010b37** [NathanWalker/angular-seed-advanced#23]
Hi, - first off love the project!

The original seed project uses linkages like this
    templateUrl: './login.component.html',
    styleUrls: ['./login.component.css'],

But the currect advanced one uses
  templateUrl: './components/login/login.component.html',
  styleUrls: ['./components/login/login.component.css']

when I think it should be as the original above.

This is also causing the production build to break as it causes the builder to then look for files like this:
C:\work\ng2-adv\dist\tmp\components\login\components\login\login.component.html

Or am I just doing it wrong?

**Comment by NathanWalker** [comment]
@red010b37 Thanks for this report. I'm investigating this.
The usage of the full url vs. relative is intentional and due to how nativescript is integrated.
However, I'm seeing something else wrong with the `prod` build. I'll try to fix this in next couple days (or tonight if I can).

**Comment by NathanWalker** [comment]
ok @red010b37 prod build works now. If you pull latest, then do the following:

```
rm -rf node_modules
rm -rf typings
npm install
npm run build.prod
npm install -g simplehttpserver
simplehttpserver dist/prod
```

This will start a server of the production build. Then open your browser to `http://localhost:8000` to see it. 

The `dist/prod` folder can then be deployed to any server.
Again, component `templateUrl` in this seed will always be full paths vs. relative to component due to NativeScript integration.

Let me know if you still have trouble.
