### ISSUE TITLE
npm run start.ios iOS 10 app instantly crashes.

### ISSUE THREAD

**Issue by detectedstealth** [NathanWalker/angular-seed-advanced#230]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_
Download/install Xcode 8
Pull latest code for this repo

**Current behavior**
When running: `npm run start.ios`

```
** BUILD SUCCEEDED **

Project successfully built
Successfully deployed on device with identifier 'FA16BF28-6115-4623-A392-EAEEA6C5B53D'.
Sep 14 08:14:19 dev com.apple.CoreSimulator.SimDevice.FA16BF28-6115-4623-A392-EAEEA6C5B53D.launchd_sim[14770] (UIKitApplication:com.yourdomain.appname[0x1128][16698]): Service exited due to Trace/BPT trap: 5
```

Also when clicking on the app in the simulator to open it you see the nativescript app icon then the app closes instantly. 

**Expected/desired behavior**
Expect the base app to run as it does on Android, Desktop and web.

**Other information**

**Comment by netwiser** [comment]
Same issue here, EI Captain with Xcode 8.0 8A218a

**Comment by asterizk** [comment]
Same here, on same setup: El Capitan [10.11.6 (15G1004)] with Xcode 8.0 8A218a.

**Comment by fourctv** [comment]
FYI, I have that exact setup (El Capitan [10.11.6 (15G1004)] with Xcode 8.0 8A218a.), and it works fine here!

Have you tried to do `npm run clean`, to clean up everything after a merge and then try to run it again?
Or grab a clean seed and try to run the emulator, to see if it is a problem with your app or your OSX/XCode environment?

Struggling with my stuff, but seed runs fine on simulator.

**Comment by asterizk** [comment]
Thank you for the reply.  It may actually just be my stuff, which is based off the seed. Will try clean seed & report back. Kind of green in this dev environment so please forgive excess noobosity.

**Comment by fourctv** [comment]
while looking for something else I bumped into a bunch of people complaining about XCode 8 and iOS10, where their apps would crash immediately on simulator. Not related to {N} at all.

So, that might be your case...

One of the suggestions there were:

```
One of methods how to resolve that is:
- Close Xcode
- Go to: /Users/YourOSXUserName/Library/Developer/Xcode/DerivedData
- Delete all folders from "Driver Data"
- Open Xcode, open project and build again.
```

(https://forums.developer.apple.com/thread/48959)

hth

**Comment by asterizk** [comment]
Just a quick followup, the clean seed indeed launches correctly on my setup (El Capitan [10.11.6 (15G1004)] with Xcode 8.0 8A218a), so the problem must be with my project... thanks for your help @fourctv, I will give your other suggestions a try :)

**Comment by detectedstealth** [comment]
I started from scratch again following the: https://github.com/NathanWalker/angular2-seed-advanced#how-best-to-use-for-your-project

And it worked as expected this time.

**Comment by asterizk** [comment]
@fourctv While I've got a /Users/YourOSXUserName/Library/Developer/Xcode/DerivedData/ directory, I don't see anything inside there labeled "Driver Data", so I'm at a loss. I'll keep poking around.  Thanks very much for the suggestions, it's appreciated.

**Comment by asterizk** [comment]
Okay, an update.  At this point my "Service exited due to Trace/BPT trap: 5" error is gone.  See below for how:

This post: https://bugzilla.xamarin.com/show_bug.cgi?id=43830 helped me find the crashlogs for my app.  Vincent Dondain:

> My guess (and if it's the same issue I had before where the device logs showed `Service exited due to Trace/BPT trap: 5`) is that there should also be a crash report.
> In the Mac's Console app check if there are any "User Diagnostic Reports". There you should see some Dyld Error Message with a reason "no suitable image found".

I found my crash reports at `/Users/MYUSERNAME/Library/Logs/DiagnosticReports/`. Inside there, I found a bunch of log files named like this:
- `nativescript_2016-09-23-150826_MACHINENAME.crash`

Looking at the most-recent, I was able to find this as the root cause:
- `Library not loaded: @rpath/TKLiveSync.framework/TKLiveSync`

Armed with this new info, searching the web, I found this: https://github.com/NativeScript/NativeScript/issues/2750

There, roblav96 said:

> Resolved. Completely uninstall xcode and nativescript.  Then do:
> 
> ```
> npm install -g nativescript@next
> tns create test
> cd test
> npm install tns-core-modules@next
> tns platform add ios@next
> tns run ios
> ```

Later in that comment thread, roblab96 indicates this as the root cause:

> updating everything tns related to next branch resolves my issues. but the stable branch of 2.3.0 produces these errors for me.

So I'm going to give his approach a try.

Steps I used (roughly followed this: https://docs.nativescript.org/releases/running-latest#getting-the-latest-development-version-via-npm ):
1. cd MYPROJECTFOLDER
2. npm uninstall -g nativescript
3. npm install -g nativescript@next [when asked if I want to visit the official docs and run the setup script: no to both]
4. cd nativescript
5. tns plugin add tns-core-modules@next
6. tns platform remove ios
7. tns platform add ios@next
8. cd ..
9. npm run start.ios

At this point, I'm running now running into "Service exited due to Segmentation fault: 11":

```
** BUILD SUCCEEDED **
Project successfully built
Successfully deployed on device with identifier '7914E768-B440-490E-8179-36FDDDBB5986'.
Sep 23 16:18:04 MACHINENAME nativescript[83339]: objc[83339]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x124c16910) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x124a40210). One of the two will be used. Which one is undefined.
Sep 23 16:18:05 MACHINENAME nativescript[83339]: 1   0x10e0698d7 -[TNSRuntime executeModule:]
Sep 23 16:18:05 MACHINENAME nativescript[83339]: 2   0x10dbd66c2 main
Sep 23 16:18:05 MACHINENAME nativescript[83339]: 3   0x11258168d start
Sep 23 16:18:05 MACHINENAME nativescript[83339]: file:///app/shared/app/services/sound-native.service.js:4:42: JS ERROR Error: Could not find module 'nativescript-sound-player'. Computed path '/Users/MYUSERNAME/Library/Developer/CoreSimulator/Devices/7914E768-B440-490E-8179-36FDDDBB5986/data/Containers/Bundle/Application/340360D0-4D0E-4BD2-B519-E1290B16E870/nativescript.app/app/tns_modules/nativescript-sound-player'.
Sep 23 16:18:05 MACHINENAME com.apple.CoreSimulator.SimDevice.7914E768-B440-490E-8179-36FDDDBB5986.launchd_sim[82939] (UIKitApplication:com.yourdomain.appname[0x1afb][83339]): Service exited due to Segmentation fault: 11
```

I haven't yet tried uninstalling Xcode but at this point I think my problems are due to my code trying to use nativescript-sound-player, which isn't available for iOS, rather than some system-level failure.  If I figure anything else out, will update here.  Thanks again for everyone's help.

Again, my config: (El Capitan [10.11.6 (15G1004)] with Xcode 8.0 8A218a).
