### ISSUE TITLE
is moduleId: module.id a good or bad idea?

### ISSUE THREAD

**Issue by Sn3b** [NathanWalker/angular-seed-advanced#25]
Hey I've just noticed you don't use moduleId: module.id at the top, is there a reason?

I've seen it allows referencing html and css files relatively:

``` javascript
@FormComponent({
  selector: 'sd-home',
  moduleId: module.id,
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
```

instead of:

``` javascript
@FormComponent({
  selector: 'sd-home',
  templateUrl: './components/home/home.component.html',
  styleUrls: ['./components/home/home.component.css']
})
```

**Comment by NathanWalker** [comment]
Good question and I should probably mention this in the`README`.
Due to the NativeScript integration and necessity to swap view paths out at runtime for {N} XML equivalents, the full path is needed to map to an appropriate matching view location in the `nativescript.framework`, therefore relative paths are _not_ used like they are in the parent seed.

I'm not sure this will change here anytime soon, so I will close this issue for now.
Down the road, it may become possible to handle differently.

**Comment by Sn3b** [comment]
Ok thanks! :)
