### ISSUE TITLE
Support for npm @types

### ISSUE THREAD

**Issue by sqwk** [NathanWalker/angular-seed-advanced#257]
I added `typeRoots` to both `tsconfig.json`s to support typescript 2.0s npm types. This works fine for the editor (Visual Studio Code), but the typings are not picked up during the build.

```
{
    "compilerOptions": {
        ...
        "typeRoots": [
            "../node_modules/@types"
        ]
}
```

Adding something this to `src/client/typings.d.ts' will solve the build problems:

```
/// <reference path="../../node_modules/@types/interact.js/index.d.ts" />
```

What can be done to pick up the installed typings under `node_modules/@types`automatically?

**Comment by NathanWalker** [comment]
@sqwk try adding a `types` key after `typeRoots` in the root `tsconfig.json` and you won't need the reference. For example:

```
"typeRoots": [
      "./node_modules/@types",
      "./node_modules"
    ],
    "types": [
      "node",
      "interact.js"  <--- this is the folder name of the @types you have installed
    ]
```

The build uses the tsconfig so should work well with VS Code in addition to the build.
Just add folder names of the `@types` you install to that collection in the config as you add more.

**Comment by sqwk** [comment]
Thanks that works fine … (I also had to check out the latest version of master)

**Comment by viktorstaikov** [comment]
Hi,
I'm facing pretty similar issue, but the fix above doesn't work for me.
The case is that I'm trying to integrate __Everlive SDK__ in the project. It relies on __underscore__ for some reason.

I've tried three approaches here:
1. Install __underscore__ using __typings__ at _./trypings_ and add the path to tsconfig.json
2. Install __underscore__ using __npm install @types/underscore__ and again add it to tsconfig.json
3. Use the __underscore__ typings from __everlive-sdk__ package, still not working

After some debugging, I saw that the gulp task looks for typings in _./tools/manual_typigns_. When I move my typings there, the error disappeared.

Not sure if that the intended behaviour or I'm missing something, because it looks kind of odd to me.
