### ISSUE TITLE
Google Analytics instead of Segment

### ISSUE THREAD

**Issue by sqwk** [NathanWalker/angular-seed-advanced#261]
Is there a guide on using Google Analytics instead of Segment with angulartics2 in this seed?

In `analytics.service.ts`I changed the segment import for the following:

```
import { Angulartics2GoogleAnalytics } from 'angulartics2/src/providers/angulartics2-google-analytics';
```

 and replaced all mentions of `segment: Angulartics2Segment` with `ga: Angulartics2GoogleAnalytics`.

The pageTrack method had to be changed as follows:

```
public pageTrack(path: string, location: any) {
    if (!this.devMode()) {
        this.ga.pageTrack(path);
    }
}
```

The tracking code supplied by Google was included in `index.html` (removing the `ga('send', 'pageview');`)

However, no hits are logged in production mode. Is there something else that needs to be turned on?

**Comment by NathanWalker** [comment]
You can either use Google analytics directly by just including the ga snippet in `index.html` and write your own wrapper service or use the angulartics2 integration which you have tried there.

I would recommend stepping through the code with a debugger to follow the tracking you are after with your integration setup there. Since this is outside scope of the seed and just an integration swap with the angulartics2 plugin, I would refer you here for guidance on how to do that:
https://github.com/angulartics/angulartics2

There's nothing specific the seed does other than the `analytics.service` which you have made the right changes to it appears. You may try stepping through your pageTrack call to determine what is happening.
