### ISSUE TITLE
Could not find module 'parse5/index' with npm run start.ios

### ISSUE THREAD

**Issue by netwiser** [NathanWalker/angular-seed-advanced#266]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**
npm i nativescript@next -g
check out the latest angular2-seed-advanced
cd angular2-seed-advanced
npm install
npm run start.ios

_What steps should we try in your demo to see the problem?_

**Current behavior**
file:///app/tns_modules/nativescript-angular/parse5_adapter.js:8:21: JS ERROR Error: Could not find module 'parse5/index'. Computed path '/Users/netwiser/Library/Developer/CoreSimulator/Devices/C02DE6EC-2A02-4754-8830-490645792745/data/Containers/Bundle/Application/DC03B4BD-DA1C-45D4-B3AD-B4F4BC4D22B8/nativescript.app/app/tns_modules/parse5/index'.

**Expected/desired behavior**
Emulator up and run

**Other information**
MacOS, Xcode 8, Node 6.6.0, npm 3.10.3, nativescript 2.4.0-2016-10-11-6790

**Comment by NathanWalker** [comment]
Thanks for the report @netwiser, I also see this issue and have reported it here:
https://github.com/NativeScript/nativescript-angular/issues/493

**Comment by ajanytime** [comment]
Im having the same issue here,

1: a fresh clone
2: npm i
3: npm run start.ios

result,

Oct 13 23:00:35 AJs-MacBook-Pro nativescript[24777]: objc[24777]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11d5b7910) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x11d3e1210). One of the two will be used. Which one is undefined.
Oct 13 23:00:35 AJs-MacBook-Pro nativescript[24777]: 1   0x1069a6940 -[TNSRuntime executeModule:]
Oct 13 23:00:35 AJs-MacBook-Pro nativescript[24777]: 2   0x1065546d2 main
Oct 13 23:00:35 AJs-MacBook-Pro nativescript[24777]: 3   0x10a3a768d start
Oct 13 23:00:35 AJs-MacBook-Pro nativescript[24777]: file:///app/app/frameworks/i18n/services/multilingual.service.js:21:30: JS ERROR SyntaxError: Importing binding name 'EventEmitter' is not found.
Oct 13 23:00:35 AJs-MacBook-Pro com.apple.CoreSimulator.SimDevice.84EDE544-20CB-4192-ABED-7945A0610B67.launchd_sim[24587] (UIKitApplication:com.yourdomain.appname[0xe913][24777]): Service exited due to Segmentation fault: 11

**Comment by NathanWalker** [comment]
This error is now gone on master.

Another issue has cropped up related to ng2-translate, please see this comment:
https://github.com/NathanWalker/angular-seed-advanced/issues/272#issuecomment-253722878
