### ISSUE TITLE
Enabling Sass causes build.html_css to hang

### ISSUE THREAD

**Issue by SNelson79** [NathanWalker/angular-seed-advanced#286]
#182 Following this quick issue, which instructs to put `this.ENABLE_SCSS = true;` in the `project.config.ts` file.  

Once I do that and I execute any script to dev on, the build process hangs indefinitely on `build.html_css` and `node.exe` sits at about 13% processor and no memory usage changes.

Digging further into `build.html_css` and output log info I've determined it hangs at this point:

```
function processAllExternalStylesheets() {
  //...snip...  
  return stream.pipe(gulp.dest(Config.CSS_DEST));  <=== Does not continue after this
}
```

Thanks for the help in trying to track this down

**Comment by SNelson79** [comment]
We were merging in another project into the seed and one of our scss was importing a file that wasn't available.

It was painful to track that down, too bad the build process doesn't yell out that it's missing a file instead of just hanging on the build.

**Comment by Sn3b** [comment]
How have you managed to find out which file was causing the issue?

I'm facing something similar :(

**Comment by Kaffiend** [comment]
Maybe these are related to #292?

**Comment by Sn3b** [comment]
Not sure, I'm new to SASS so still trying to figure out how the pieces fit together :)

**Comment by Kaffiend** [comment]
Still having issues after #292 was fixed?

**Comment by Sn3b** [comment]
Yes I still get it every now and again, but I'm trying to merge another project into this one with various dependencies and I'm wondering if it isn't the scss files from that other projects that are faulty. I sometimes need to manually delete the generated css folder and re run npm start to fix it...

**Comment by Benjman** [comment]
Late to the show, but I found this when trying to fix my hanging problem. Go through all your scss files to make sure a variable isn't referencing something that doesn't exist anymore.

I got this problem when I moved from bootstrap to MDL, and there was a reference to a bootstrap variable in one of my scss files that didn't exist anymore. Instead of an npm error, build.html_css would just hang. After checking all my scss files, I found several references that didn't exist anymore. Fixing them fixed the build from hanging.
