### ISSUE TITLE
Remove custom decorators: provide build hooks for templateUrl swap and style mode

### ISSUE THREAD

**Issue by NathanWalker** [NathanWalker/angular-seed-advanced#296]
The history around the seed's usage of custom decorators were largely for:
1. Relieving the burden of specifying same `directives` across many different components that needed certain sets globally. *No longer needed since @NgModule was introduced*
2. Allow `templateUrl` to be auto-swapped with platform specific template. 

Since #1 is no longer an issue, the need for custom decorators has diminished.
#2 could be solved be a simple build hook step in *build.dev.js* instead.

Custom decorators *at the moment* can not be used with AoT compilation. This may change in the future but given the diminished reasons above, I'd like to remove them altogether.

The only thing that leaves is `encapsulation` metadata. The decorators were a nice way to turn on `ViewEncapsulation.None` globally for all components when a single global stylesheet was desired over component level style encapsulation. However that too could also be cured by a simple build step and `project.config` setting.

I will likely work on removing custom decorators altogether in near future, just heads up.

**Comment by m-abs** [comment]
Hi @NathanWalker,

I've been playing around with removing the need for BaseComponent, it's mostly meant as a proof-of-concept.

The motivation is that we wanted to use webpack bundles for {N} and we have some really annoying problems caused by the symlinks (livesync and typing errors from tsc).
I also wanted to keep the web-component html/css and the source ts-files out of the {N}-build.

https://github.com/m-abs/angular2-seed-advanced/tree/playing-with-build

I've:
- removed BaseComponent from all components
- remove nativescript-dev-typescipt
- installed nativescript-dev-webpack
- Moved {N} source code from `nativescript/app` to `nativescript/src`
- Added gulp tasks for copying assets, building ts and css/scss for {N}.
  - Component tns.css/html-files are renamed from `widget.component.tns.html` => `widget.component.html` so we don't need `BaseComponent`-anymore
- gulp ignores tns.css/tns.html-files for web builds.

Build ts for {N}: `gulp build.tns`
Building the {N}-app: cd nativescript && tns run android

Due to https://github.com/NativeScript/nativescript-dev-webpack/issues/10, I couldn't get webpack to work.

This is mostly meant as a proof-of-concept for something we've been debating in our dev-team, but it looks promising although it could/should be much cleaner than this :)

**Comment by m-abs** [comment]
Hi again,

Updated version:
https://github.com/m-abs/angular2-seed-advanced/tree/playing-with-build-3

    Changes:
    * nativescript-dev-typescript have been removed
    * nativescript-dev-webpack have been installed
    * {N} sourcecode have been moved from nativescript/app
      to nativescript/src, including App_Resources and symlinks
    * The nativescript/app/assets symlink have been removed, these files are
      copied by gulp-tasks.
    * To build the {N}-app you now have to run:
      gulp build.tns && cd nativescript && tns build android --bundle
    
    Gulp tasks:
    * gulp clean.tns:
      * Empties nativescript/app
    * gulp build.tns_html_css:
      * Copies the *.tns.html/css-files to nativescript/app and removed
        'tns' from their filename. This is to remove the need for @BaseComponent
    * gulp build.assets.tns:
      * Copies files from src/client/assets to nativescript/app/assets
    * gulp build.js.tns:
      * Gulp transpiles TypeScript from nativescript/src to nativescript/app
        Note: tsconfig.json have been moved to nativescript/src/tsconfig.json
    * gulp watch.tns:
      * Watch for changes for the {N}-app
    * gulp build.tns:
      * Groups: build.tns_html_css, build.assets.tns, build.js.tns
    * gulp build.tns.watch:
      * Watches with watch.tns and runs build.tns on changes

Diff: https://github.com/NathanWalker/angular-seed-advanced/compare/master...m-abs:playing-with-build-3

**Comment by NathanWalker** [comment]
@m-abs That is very exciting work there! 
I'll try to take a look soon and see if I could help figure out remaining issues there.
When this works, I would definitely be interested in merging this to master.

**Comment by NathanWalker** [comment]
This is complete now. Huge thanks to @m-abs !
