### ISSUE TITLE
e2e tests compiled with different tsconfig.json

### ISSUE THREAD

**Issue by VladimirMakaev** [NathanWalker/angular-seed-advanced#305]
We want to build rich suite of e2e tests leveraging async/await feature of TypeScript which is only available for ES2015+ target

To do that we need separate tsconfig.json used for building e2e specs. But it's currently not seem to possible with the current seed structure.

Do you have plans to address this problem in the near future? Can you share your thoughts how would you implement that? We probably will be able to contribute that back to the seed project

**Comment by NathanWalker** [comment]
@VladimirMakaev That sounds exciting and fun.

You could take a look here:
Instead of using the `makeTsProject` function https://github.com/NathanWalker/angular-seed-advanced/blob/master/tools/tasks/seed/build.js.e2e.ts#L16, you could export a new function that uses a different tsconfig.json specified here https://github.com/NathanWalker/angular-seed-advanced/blob/master/tools/utils/seed/tsproject.ts#L21 which you could put anywhere you see fit, but likely inside tools might make sense as it would be a custom config used only by e2e specs for instance.

**Comment by VladimirMakaev** [comment]
@NathanWalker Thanks for your suggestion.

I was thinking about reusing `makeTsProject`. I can extend it to add optional argument of `projectName` which could be `tsconfig.json` by default.

Another thing is that for VSCode to properly recognize another `tsconfig.json` we need to move e2e-specs outside of `src/client` folder. (E.g. `src/e2e`). I would move all e2e specific framework stuff (e.g. `e2e/dropdown.ts`) there as well

Let me know your thoughts on this

**Comment by NathanWalker** [comment]
On master now 👍
