### ISSUE TITLE
Record video explanations

### ISSUE THREAD

**Issue by NathanWalker** [NathanWalker/angular-seed-advanced#32]
- explain test providers; why/how
- explain how teams can setup reusable test scenarios
- explain test shorthand

**Comment by OscarAgreda** [comment]
I will suggest to start the video , telling the viewers they have to follow the steps from the ReadMe page under  **Usage**. Because the steps work fine , are so easy to follow , take some time to complete and the viewer must do his/her homework. 
then , in my opinion 

-how to add a custom page 
-how to have the client app communicate to a http endpoint.
-make an allusion that is the pro version of `https://github.com/mgechev/angular2-seed`
-show the results of creating and removing a new framework for the app in `src/client/app/frameworks`
-explain the awesome power of the **NativerScript** engine , 
-briefly talk about how **Electron** helps the seed and how to always keep the app in sync with Eelectron.
-and yes `setup resusable test scenarios`

IMHO.
regards

**Comment by NathanWalker** [comment]
Really really appreciate this suggestion @OscarAgreda, part of the reason I have procrastinated recording the video is I keep going back/forth on what should be highlighted in a help video.
This helps a ton and totally agree.

**Comment by OscarAgreda** [comment]
Thank you :100: 

Also, the first thing a user of this the template will need, is the ability to implement **nativeScript** PLUGINS; camera , location via GPS, keyboard, etc for example .
in the past, all we had was the apache cordova + ionic system., in which plugins was a painful experience , so thank you for this seed, once again.

now, regarding Electron , is it possible to use the **autoUpdater**  so when the developer changes the app and re-deploy, the end-user running the desktop version of it, will receive an alert to update. Therefore making it real to **keep just one Codebase**  with several front ends (desktop. mobile and web).

**Comment by OscarAgreda** [comment]
Hello @nathanwalker 
Any news on the video. 
It will be such a blessing  seing this seed come to life under your fingers and explanations.

**Comment by NathanWalker** [comment]
Hi @OscarAgreda due to some refactorings this was placed in long delay. There is one more refactor that will take place over the next week and after that, it should clear the way to record some videos. Thanks for the ping.

**Comment by OscarAgreda** [comment]
Hello @NathanWalker  any news on the refactoring ?

**Comment by NathanWalker** [comment]
@OscarAgreda so sorry for delay in these videos. They take time to do well and have not had ample time this summer to produce them. If you have any specific questions, feel free to ask though.

**Comment by lindsaymarkward** [comment]
Just want to add that I'm looking forward to the videos. I saw your nativescript-ng2-magic one and you did a great job. Now that Angular 2 is final... let's do it ;)

**Comment by NathanWalker** [comment]
I plan to cover this seed in depth in a future egghead.io course.
