### ISSUE TITLE
Remove ng2-config 

### ISSUE THREAD

**Issue by NathanWalker** [NathanWalker/angular-seed-advanced#331]
@fulls1z3 Would love your thoughts here but I am considering removing ng2-config.
I like it however I've found some limitations that make it a bit troublesome. For instance, a lot of config settings are needed before `ngOnInit` like an api url config that may be needed during early phase launch of app before ng init time.

It also encourages exposing certain config settings via a public resource which adds another `GET` request to the app. Some of these config settings that users may play loose with should probably not be exposed via a public config file such as this. Thoughts?

**Comment by fulls1z3** [comment]
Hi @NathanWalker, I can understand the reasons to remove ng2-config from the context of angular-seed-advanced. I have just posted #327 about the steps to be taken to solve the situation.

Meanwhile, it's true that there're several limitations in ng2-config - such as required config settings before `ngOnInit`. It's all because the workflow of APP_INITIALIZER, and as a solution we pass the params from config to the loaders (ex: static loader in ng2-translate) so that the initializations are happening right at `ngOnInit`.

It's possible to load those settings to JS window object before systemjs/webpack processes the angular code, and init the ng2-config once (by moving from JS window object to ConfigService instance) - the first time these values are accessed. But this approach caused severe problems in AoT (statically analyzableness). As a solution, I've decided to place the `GET` request during app initialization.

Another issue about the config settings, they're exposed to public. It's also true. However, any value we use in angular is exposed to public (a config json file, or a config ts file). The config file (or API) can be secured - but again they will be exposed at least right at the place they're used.

So my current focus is on ng2-config with rxjs 5.0.2. The decision to remove ng2-config, I leave it to you.

**Comment by NathanWalker** [comment]
@fulls1z3 Thanks I will remove for now until other things can be redressed later as not to inconvenience anyone. In a future PR we can ensure more things are corrected. Will post an update to master shortly.

**Comment by fulls1z3** [comment]
Hi @NathanWalker, I just wanted to let you know I still hold a local copy of angular-seed-advanced integrated with ng2-config, and making fixes on it. These fixes are not only dedicated for angular-seed-advanced - but also for the project I'm currently developing. Basically, my project depends on angular-seed-advanced's framework, and I think angular-seed-advanced can also benefit from any features of this project.

As far as I've progressed, I'm carrying the initializers (such as i18n) to constructor level from `ngOnInit` - when avabilable. And I've observed that it allows access to multilanguage values earlier than it was initialized with `ngOnInit`.

Meanwhile, the project I'm working on integrates angular-seed-advanced with ng2-translate, ng2-config, ng2-metadata and localize-router (from Greentube). Also, benefits more from ngrx. I'll try to provide you a preview (without committing to master) to give you a better idea, and ofc benefit from your feedback for all those possible additions.

On the other hand I'm watching the news with #327, and found out the 2.4.0 stability interjection update of angular caused inconsistencies in other areas as well as with http.map method of rxjs. Before suggesting any solution for that issue, I'm still intensively analyzing the current situation and any other interference.

**Comment by fulls1z3** [comment]
Hi @NathanWalker,

I've got good news. I was able to reproduce errors such as "...map is not a function" or "...switchMap is not a function" on different places (even under ngrx effects), and was able to solve these problems. As far as I've noticed, they've caused because of rxjs (>=5.0.0). Importing "map" or "switchMap" from rxjs seems to solve the errors.

Furthermore, I've succeeded initializing multilingual values before the `ngOnInit`.

So let's discuss whether provide a PR or not, about this.

Cheers :)
