### ISSUE TITLE
ATTN SEED USERS: Good news! Custom decorators removed - some reorganization

### ISSUE THREAD

**Issue by NathanWalker** [NathanWalker/angular-seed-advanced#337]
* No more custom decorators
* Can just use standard `@Component` from `@angular/core`
* Template switching for NativeScript done using clever concurrent gulp task and leveraging npm scripts for {N} app
* AoT builds available for {N} app via Webpack with: `npm run build.ios` and `npm run build.android`
* Livesync improved for {N} development

Best way to move forward:

Instead of merging in these changes (btw you can! - you may have some merge conflicts), you could just download a new copy of master and follow [this](https://github.com/NathanWalker/angular-seed-advanced#how-best-to-use-for-your-project). Then can just drop your customized app code back in place.

This setup is vastly better than previously using custom component decorators since they could not be used with AoT builds for the web. Additionally the ability to create AoT builds of {N} app is made possible with the most recent merged PR.

**Comment by richarddavenport** [comment]
@NathanWalker @mgechev This project is so awesome! You guys have done such a tremendous job. I'm finding myself spending quite a bit of time reading and I would love to contribute by helping the docs. I think having a beefed up wiki (on github) or even a simple static site to point people to (gh pages) would go a long way. One other thing that I wish existed (maybe it does?!) is a gitter or slack team that people could go to with questions or guidance. I know I would certainly use it.

Let me know if I could help, I would love to be apart of the team!

**Comment by NathanWalker** [comment]
Hi @richarddavenport, it's always nice to hear when someone has gotten a lot out of it. Thank you.
It's certainly been a long standing passion project somewhat constantly in the works and improving (most of it through experimentation - at least the feature integrations here specifically). As always much credit to @mgechev for the underlying foundation which is infinitely scalable and extensible.

I agree. There should be more clean/concise documentation around several things here. Some of the reasons a lot of docs have not been outlined as of yet is because some ideals were continually being worked on so documenting at that point would have just created more work and more confusion later. We are at a point now that is starting to make sense to conclude some docs.
Some of which I have provided here just now:
https://github.com/NathanWalker/angular-seed-advanced#code-organization-overview

Always welcome to more docs on various other things. Many areas could be elaborated on like extending and providing mobile specific services to override shared web services where needed.

There actually is a Slack channel for this seed (`angular-seed-advanced`) once in this group:
http://developer.telerik.com/wp-login.php?action=slack-invitation

I never setup a gitter channel because I am too busy and wouldn't want to let people down with blank answers. However the Slack channel above provides a place for other users to share experiences and answers etc.

As always, love to hear any suggestions to improvements. Thanks again.

**Comment by richarddavenport** [comment]
I just realized you're _the_ Nathan Walker that did the NativeScript course on Egghead.io. Just watched it a week or so ago. Great job!

**Comment by jlooper** [comment]
We also have a forum category for this awesome seed! http://forum.nativescript.org and check out the Web and Mobile Shared Code category if you want to pose questions. More info here: http://forum.nativescript.org/t/about-the-web-and-mobile-code-sharing-category/228

**Comment by NathanWalker** [comment]
Thanks @jlooper ! Yes that forum is the best place for discussion and questions! 👍

**Comment by jlooper** [comment]
Quick ping on this change...I downloaded it and tried to run, but I think there's an issue wtih nativescript-dev-webpack, which isn't installing properly (perhaps because of pathing issues?)

```
> nativescript-dev-webpack@0.3.2 postinstall /Users/Looper/Desktop/angular-seed-advanced-master/nativescript/node_modules/nativescript-dev-webpack
> node postinstall.js

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/Looper/Desktop/angular-seed-advanced-master/nativescript/app/vendor-platform.android.ts'
```
It's looking in the /app folder, but I think it should be /src?

**Comment by NathanWalker** [comment]
@jlooper was this a fresh download of master and just running `npm i` in root?

**Comment by Swiftwork** [comment]
@jlooper @NathanWalker I have spent best part of my day tracking this down and believe it is due to the fact that [nativescript-dev-webpack](https://github.com/NativeScript/nativescript-dev-webpack/blob/79286a6f53570844fc2a8fd28c073221c920e7db/installer.js#L6) is looking for the **app** dir which has now been renamed **src** in angular-seed-advanced, but I could be wrong ;)

*Note: this is a merge from upstream/master into my local branch so mistakes could have been made. Windows 10, Node 7*

**Comment by krisloekkegaard** [comment]
Fresh download and following the [setup steps](https://github.com/NathanWalker/angular-seed-advanced#how-best-to-use-for-your-project) in the readme works for me @jlooper @NathanWalker. 

However, at step 5 `npm run git.merge` I got some git errors saying that some files would be overwritten by the merge. I deleted the files in question from disk and everything worked from there. The files were:
```
nativescript/tools/webpack/tns-loader.js
nativescript/webpack.android.js
nativescript/webpack.common.js
nativescript/webpack.ios.js
```
I also had an error saying  the package was invalid when deploying to my Android device the first time, but after adjusting the package id/name it went away. That may have been related to previous settings or installations on my particular device. Web and iOS worked out of the box.

And just to add to the general comments: this project is fantastic and I have been looking forward to this particular update like it was Christmas :) Having livesync back for {N} makes all the difference!

Thanks so much for all the great work and special shout-out to @m-abs as I think he contributed a lot here.

**Comment by jlooper** [comment]
@nathanwalker it's a fresh new install and @swiftwork that was my impression too

**Comment by NathanWalker** [comment]
@jlooper @Swiftwork @krisloekkegaard 'How best to use for project section` has been greatly simplified now and verified to work with latest changes:
https://github.com/NathanWalker/angular-seed-advanced#how-best-to-use-for-your-project
(refresh the page to ensure you're looking at new instructions - removed all the npm scripts for git, wasn't needed anymore - much simpler :thumbsup:)

**Comment by jlooper** [comment]
@Swiftwork Here's a rundown of how Nathan and I got this puppy working today! 

1. Update node and npm. My versions weren't up to par; you need node 6.9.1 and npm 3.10.9.
2. It's preferable to upgrade node by using nvm. Instructions are [here](http://yoember.com/nodejs/the-best-way-to-install-node-js/), and this is smart going forward as you can pick and choose the version of node you need.
3. Once you upgrade, redo the npm install. Note, you may need to upgrade node-sass if that part errors, but this is a quick fix, just follow the instructions in the error message.

**Comment by Swiftwork** [comment]
@jlooper I have everything but possibly npm up to date, but I will download a fresh master this evening and see what differs from my own and if I can get that working. Maybe I will migrate my changes to the fresh copy as well.

@NathanWalker I've previously been working on a Mac but I have since swapped over to my Windows desktop. I'm not sure Windows is supported, but some of the scripts in the nativescript folders package.json won't work. rm -rf and mkdir -p are not DOS commands. I could run a bash terminal instead, but thought I would let you know.

**Comment by m-abs** [comment]
@Swiftwork Sorry that `rm -rf` and `mkdir -p` is my fault.
All the windows devs I work with have a working bash shell, so I didn't consider non-bash shells.

Do you know of a platform independent way to do the same?
`mkdir -p` creates the path including parents paths and doesn't fail if the dir already exists. It's used to avoid errors installing nativescript-modules that expect the app-dir to exist.
`rm -rf` just removes a directory and all its content. Maybe it could be replaced with `rimraf` from npmjs.

**Comment by Swiftwork** [comment]
@m-abs yeah, I usually have that as well, but just swapped pc, therefore it wasn't setup yet. I don't know if it is a good idea to use npm packages for that but **rimraf** and **mkdirp** are solutions that could be used. I guess it depends on if you want out of the box functionality or if you want to require a bash alternative.

**Comment by krisloekkegaard** [comment]
I was getting some errors and unexpected behavior related with change detection when dropping our components from the old structure into the new. I believe the reason is that without the `BaseComponent` decorator, `OnPush` is no longer used by default.

It's a quick fix by setting the change detection strategy on each component as you are anyway going through and removing the `BaseComponent` decorators, but just thinking it might make sense to update the sample components and perhaps the docs to highlight this. Especially for people coming from the old structure.

**Comment by NathanWalker** [comment]
@krisloekkegaard good point - thanks for bringing that up - yes, `OnPush` is *not* enabled by default any longer as that has proven too difficult for the large majority of cases and it is not advisable to have it enabled everywhere. Only enable it for components that you want to dial performance cases with.

**Comment by codeback** [comment]
Hi @NathanWalker, amazing work!! Thank you very much.

I am having problems with custom Nativescript components. The view is rendering ok but my app crashes when I tap a button. Is it possible that the view is looking for the *.ts file that contains the handler in a wrong path?   

I am placing the component files (*.html and *.ts) in 'nativescript/src/mobile/components'.

**Comment by krisloekkegaard** [comment]
@codeback can you elaborate a bit more on what you are trying to do and perhaps share some code and/or specific error messages?

If this is not related to the latest changes in structure, perhaps it would be worth asking the question in a separate thread - either by opening a new issue here on GitHub or creating a topic in the forum @jlooper mentioned:
http://forum.nativescript.org/c/web-and-mobile-sharing

**Comment by codeback** [comment]
Hi @krisloekkegaard,  

I thought the problem was related to the new structure but I was wrong. 

I've just found out that the problem was entirely related with ngrx-store-freeze and deep cloning.

The confusion was due to the unspecified error message we were receiving.

Sorry about that!

**Comment by ghys** [comment]
This change looks great, the livesync in the {N} app is lovely! One problem I encountered on Windows just in case it ends up being useful to someone else: when building the {N} app, the `build.js.tns` task complained about missing modules in `./app`. Turns out the symlink `nativescript/src/app` pointing to `src/client/app` wasn't there. Maybe you have to run `git clone` as admin on Windows? (symlinks can only be created with an elevated prompt).

Anyways, I recreated the symlink manually with:
```
mklink /j nativescript\src\app src\client\app
```

**Comment by sparachi** [comment]
I just installed lates nodejs 7.4.0 and pulled this repo, made sure gulp, nativescript, typescript are installed. when I did npm install, I get the same exact error message as described by @jlooper 

https://github.com/NathanWalker/angular-seed-advanced/issues/337#issuecomment-274307979 

Windows 10 Home edition, Node js 7.4.0

I tried these [steps](https://github.com/NativeScript/nativescript-dev-webpack/issues/46#issuecomment-270909663) and it did not work work around was, I went ahead with `yarn install`, and did `npm run` and angular app seems to work. I am good for now, since I'm not developing any native script apps.

**Comment by Swiftwork** [comment]
@sparachi it is due to the fact that there is no longer a folder at `nativescript/app`. This used to be where the now `nativescript/src/*` files used to lie. I'm not sure why the templates, aren't copied but I believe that it has to do with permissions similar to what @ghys experienced. What you actually want is the following:

```bash
|-nativescript/app/                   # Used to be the src files
|     |-vendor-platform.ts            # I think that's the name
|     |-vendor-platform.android.ts
|     |-vendor-platform.ios.ts
|
|-nativescript/src/*                  # The rest of the src files
```

When I did a merge instead of a fresh master, I found these **three** files in my src folder instead. You might also be able to locate them inside `node_modules/nativescript-dev-webpack/`, but I'm not sure these are identical to the expected.

**Comment by m-abs** [comment]
`nativescript/app` should be created by the `preinstall`* script inside the `nativescript`-folder, this is for `nativescript-dev-webpack` that creates some files inside `nativescript/app` duing install.

The three files have been added to git inside `nativescript/src`, so we don't loose them.

*) I've only tested the script on a *NIX system with a bash shell, Windows might not support "mkdir -p" without `cygwin`.

**Comment by sparachi** [comment]
I pulled in the code on my Ubuntu 16.04, and `npm install` went through fine. `yarn install` had hiccups
[22:57:06] Error in plugin 'run-sequence(build.html_css)'
Message:
    ENOENT: no such file or directory, scandir '/home/saikarthik/Documents/xxx/node_modules/node-sass/vendor'

 and installed `node-sass` globally, and yarn install went through.

When I did `npm start `I had the same issue. Followed [steps](https://github.com/laravel/elixir/issues/601) and did `npm rebuild node-sass` finally it worked. 

As @m-abs  suggested I will try to work on my ubuntu. @Swiftwork Thanks for you reply.

**Comment by NathanWalker** [comment]
I'm going to close this now - Note the seed was also just updated to NativeScript 2.5, released today - which does away with npm livesync scripts for iOS/Android - those are now automatically handled via `npm run start.ios` and `npm run start.android` (livesync mode is the default dev workflow out of the box starting with {N} 2.5) 👍
