### ISSUE TITLE
Possibility of webpack based version of this seed

### ISSUE THREAD

**Issue by NathanWalker** [NathanWalker/angular-seed-advanced#412]
With @gdi2290 very exciting announcement made here:
https://github.com/AngularClass/angular2-webpack-starter/issues/1686

Curious what the interest is in having a webpack based version of this seed which may be based off https://github.com/AngularClass/angular2-webpack-starter

The gulp based workflow of this seed works well however some folks prefer webpack over gulp and I've always wanted to build a webpack version of this for my own purposes, just polling.

**Comment by JonnyBGod** [comment]
@NathanWalker I am maintaining a similar (not fully working, missing NS atm) version of this seed based on AngularClass's starter. [https://github.com/JonnyBGod/angular2-webpack-advance-starter](https://github.com/JonnyBGod/angular2-webpack-advance-starter)

Would be glad to collaborate on this.

**Comment by NathanWalker** [comment]
@JonnyBGod excellent! Yes will do. We may want to start from scratch when the overhaul is complete in above but I'll start to look at what you got thanks!

**Comment by hatemhosny** [comment]
I vote for the webpack version

**Comment by JonnyBGod** [comment]
@NathanWalker I am up for starting from scratch and just take what I learned from my repo.

We should start discussing the vision for the new project. What are the goals and what we don't want to do.

I was hoping at some point to make it an angular/cli extension, but this depends on the plugin architecture they will adopt. In my opinion angular/cli does what we need for web projects, just lacks the extensibility we need to enable electron and nativescript apps in the same project.

I have been also thinking on a more monorepo ([lerna](https://github.com/lerna/lerna)) style approach where we would have 3 different projects within the same repo, web, desktop and mobile. Probably easier to keep and coordinate but also easy to share parts between them.

**Comment by enjoiful** [comment]
+1 for webpack support. Webpack rocks!

**Comment by VladimirMakaev** [comment]
@NathanWalker would be nice to have this project run on webpack. We'll most likely be able to contribute as currently it's a much better foundation to move forward. We found ourselves strugling with asset size optimizations. This is an area where webpack can come in with support for tree shaking and lazy-loading

**Comment by Dutchboy** [comment]
We have to face it.... systemJS is stale.... I've given it months, combined with JSPM, and "amazing" undocumented settings, all in the waste bin... Even the NG team has evicted towards Webpack. 

And I do NOT want to sound negative!!!!! We all, you guys, everybody, are / is working to the extreme here! Every other few days there is a new release, enabling a startup of 2.5 to 4.0 seconds, with AOT... It is only frustrating to see (an)other project(s) is struggling to keep this pace....

I've followed the angular-seed with great interest since last year June, a lot has changed, and not only for the good. And now [TeamMaestro](https://github.com/TeamMaestro/angular-native-seed) comes along. Maybe shaking things up a bit, who knows....? Even though the angular-seed(-advanced) is doing a great job.....

edit - - - what I'm referring at is that it takes more than a month, while other projects are showing perfect results with AOT, with lazy, and with 2.5 to 4 seconds boot time... Why don't we all sit together - one day - virtually, mics on, video on, dedicated, and deliver a ridiculous and perfect seed? My suggestion....

**Comment by NathanWalker** [comment]
For now definitely take a look here:
https://github.com/TeamMaestro/angular-native-seed

Just as proof of concept and for more options the expansion of AngularClass seed may happen in future.
