### ISSUE TITLE
New name : ANELO

### ISSUE THREAD

**Issue by phackwer** [NathanWalker/angular-seed-advanced#413]
I don't know if you did it on purpose, but the logos made the word ANELO popup to me. Anelo seems to be a nice name, reminds me the Portuguese and Spanish word for ring (anel/anilllo). A ring brings the idea of commitment, something cyclic and infinite. 

If you ever decide to get a more commercial name for this seed, Anelo is perfect for it.

**Comment by NathanWalker** [comment]
Haha thanks @phackwer nothing on purpose for sure.
I actually for a long time have been wanting/needing to change the graphic because Lodash is not really fitting with the core platforms shown as it just a supporting utility lib. If I end up changing the graphic I'll have to ping you to come up with a new name :)

**Comment by NathanWalker** [comment]
@phackwer recently updated graphic to be more reflective of the core stack:
https://camo.githubusercontent.com/ac95107dd03b6b7596d830837c6da48a922ecb59/68747470733a2f2f63646e2e66696c65737461636b636f6e74656e742e636f6d2f4c5357705545454751694f6443707639743652693f763d30
So perhaps we call it `NAE` :)

https://github.com/NathanWalker/angular-seed-advanced/blob/master/README.md
