### ISSUE TITLE
Add a localStorage provider?

### ISSUE THREAD

**Issue by EddyVerbruggen** [NathanWalker/angular-seed-advanced#438]
Hi,

I've been using this seed with great pleasure to create a NativeScript app with web code sharing. So thanks for maintaining this!

One thing I immediately added was a `localStorage` prodivder, much in the same way as you added `window` and `console`. Would you be interested in taking a PR that would add this to the seed? I'm sure I'm not the only with the requirement to locally persist stuff :)

FYI on NativeScript it will fall back to AppSettings, through the [nativescript-localstorage plugin](https://github.com/NathanaelA/nativescript-localstorage).

Cheers,
Eddy

**Comment by NathanWalker** [comment]
Hi @EddyVerbruggen this was discussed about a year ago here:
https://github.com/NathanWalker/angular-seed-advanced/issues/72

*However it's something that if done minimally without extraneous third party dependencies then absolutely would be nice to have here.* The issue above discussed more dependencies on the web side which I'd be careful about. The extra {N} dep would be fine as those are more focused and generally less opinionated than web libraries. I'd say as long as it's footprint is fairly small and can still be easily maintainable in the seed itself than I'm all for it!

The challenge with 3rd party dep's on the web side is due to the fast moving pace of web technologies can become time consuming to maintain.

**Comment by EddyVerbruggen** [comment]
I hear ya, and I'm simply using window.localStorage, nothing fancy and works fine for me. Always did. If folks want something more sophisticated they can always swap the web implementation for something else :)

**Comment by NathanWalker** [comment]
Perfect that would be excellent and much appreciated 👍
