### ISSUE TITLE
Is there a easy way to build modal pages both for Angular and {N}?

### ISSUE THREAD

**Issue by shiamalon** [NathanWalker/angular-seed-advanced#441]
Hi there,

I'm trying to figure our a easy way to do this but I'm not being super successful. has anyone did it? and how? 

Regards

**Comment by NathanWalker** [comment]
Hi @shiamalon yes you would want to start with creating a `PlatformModalService` which could be provided for in web with something like ng-bootstrap modals, and then in {N} you would provide the `ModalDialogService`. Lemme know if that gets you on the right track...That is what I've done in other projects with great success. I can't provide too many more details since they are part of private projects.

**Comment by renestalder** [comment]
See https://docs.nativescript.org/angular/code-samples/modal-page

Quite different from what you would do in Angular. So you'll definitively build it twice an make a logical split an some point.

**Comment by NathanWalker** [comment]
Thanks @renestalder. When sharing code with Angular to {N}, you generally want to build abstract base classes which can be extended and implemented for web or {N} or you can create Injectable service which is injected everywhere to handle modals, where this Injectable service would be provided for with a specific web version and {N} mobile version respectively.
