### ISSUE TITLE
update to latest seed?

### ISSUE THREAD

**Issue by Sn3b** [NathanWalker/angular-seed-advanced#5]
Hi,

Will you be updating this seed with all the latest changes done on the original seed?

Thanks :)

**Comment by NathanWalker** [comment]
Hopefully soon like tonight or tomorrow ;)

**Comment by Sn3b** [comment]
That'd be so great ;)

Thanks, great job btw! :)

**Comment by Sn3b** [comment]
BTW, I actually meant the whole restructuring to separate project and seed code, so that we can extend, as in use it for a real project, and continue to benefit from the seed's updates.

**Comment by dskaggs** [comment]
This goes along with a question that I had been thinking about making an issue for. The README says that you've got some more things that you'll be adding to the seed project in the future (Bootstrap is one that specifically interests me). If we start a project based on the current version of this project, what will we need to do to update it to the latest version when you add new capabilities to it?

**Comment by NathanWalker** [comment]
@Sn3b @dskaggs Now updated with latest upstream changes from `angular2-seed`.

This took awhile. Was quite a number of refactorings.
Due to all the changes, it may be best to start with a fresh clone of this if you were working with it.
There will likely no longer be that big of a change from the parent seed for awhile to come so most all should be settled now.

One big addition: this now implements [ngrx/store](https://github.com/ngrx/store) :+1:

**Comment by NathanWalker** [comment]
@dskaggs regarding bootstrap, lets address that in a separate issue (if you don't mind creating a separate issue for that specifically?) 

Lastly, I don't want to close this issue just yet as I'd like to get both of your feedback on which strategy to take now that this extensibility of the tasks and project config is in. On this pass, I put the customization here:
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/tools/config/project.config.ts

I could see this going 1 of 2 ways:
1. Keep it the way it is. Would allow users to remove certain customizations in `project.config.ts` for their specific application and/or further customize things there. Downside is if anything changes there with this `advanced` seed over time, it could cause merge conflicts with your specific project when you try to merge in latest upstream of this seed.
2. Move those customizations to bake them into the core config here (`seed.config.ts`): https://github.com/NathanWalker/angular2-seed-advanced/blob/master/tools/config/seed.config.ts
   This would allow users to merge latest upstream changes from this seed much more easily as it would not interfere with their custom project configuration in `project.config.ts`. Downside is users wanting to remove or tweak certain baked in configurations from this seed would get back to potential merge conflicts with upstream changes.

Curious what you both think.

**Comment by dskaggs** [comment]
I'm still trying to get my head around what the workflow looks like if we create a new project based on this seed project. We use BitBucket to store our repos privately. How would we start a project from this repo, remove all the sample stuff and start building our own app and then integrate changes to this repo into our project that we've been doing work on.

**Comment by NathanWalker** [comment]
Best way forward would be to:

### Setup
1. Download a zip of the seed.
2. `git remote add origin ....your private repo....`
3. `git remote add upstream https://github.com/NathanWalker/angular2-seed-advanced.git`
4. Create a new `framework` for your application in `src/frameworks` to build your codebase out. Say your app is called `Skaggs`, then create `skaggs.framework` and start building out all your components and services in there. Create other frameworks as you see fit to organize.
5. If you don't want an integration that comes out of box with this seed; for example. let's say you don't want to use i18n. Then just delete the `i18n.framework`, remove `ng2-translate` as dependency root `package.json` and `nativescript/package.json`. Then remove the references to `i18n` throughout.
6. Remove `src/components` since those are just samples and create a new folder for your components, let's say `src/pages`. It's not absolutely necessary to remove and create a new differently named folder for your components but it will make merging in upstream changes a bit smoother.

### Merging latest upstream changes
1. `git remote fetch upstream`
2. `git merge upstream/master`  // you could rebase, but it wouldn't be worth it as the conflict resolution can often be more painful if there are conflicts
3. Handle any conflicts to get latest upstream into your application. If you removed `src/components` as mentioned above, they may show back up when merging in latest upstream. You can just remove the folder again.
4. Continue building your app.

Lemme know how I can help you get started.

**Comment by Sn3b** [comment]
Super thanks for the update, was just waiting for that to start doing some real code for my project :)

As for the seed.config.ts vs project.config.ts question, what about having a 3rd file? Say, advanced.config.ts?

**Comment by NathanWalker** [comment]
@Sn3b That's an excellent idea :+1: I'll look into that.

**Comment by NathanWalker** [comment]
@Sn3b Thanks again for the great suggestion. This now exists here:
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/tools/config/seed-advanced.config.ts

Which allowed the `project.config` to just extend:
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/tools/config/project.config.ts#L5

:+1:

**Comment by Sn3b** [comment]
@NathanWalker Great! Thanks for this beautiful seed! ;)

**Comment by dskaggs** [comment]
@NathanWalker thanks for the workflow info. We'll be doing just that this week to start working on a proof of concept for our next project with this seed.

**Comment by JanOschii** [comment]
@NathanWalker If I get it right?:

"Download a zip of the seed." includes:
1. unzip the file and optionally rename the folder to something like "myfrontend"
2. Go into the folder with `cd myfrontend`
2. Call `npm install` 
3. Call `npm run setup` 

Is this correct?

**Comment by NathanWalker** [comment]
Yes.
