### ISSUE TITLE
Hello.js

### ISSUE THREAD

**Issue by Sn3b** [NathanWalker/angular-seed-advanced#55]
Just a thought, but I think integrating Hello.js would be super cool.

I can only imagine such an advanced seed would be used for advanced projects with users and stuff, and Hello.js makes using social logins really easy. The rest would be up to the backend tech of course, but a well integrated, fully client side solution for logging with facebook, google etc in your seed would be awesome :)

**Comment by NathanWalker** [comment]
Hi @Sn3b, definitely a great library and very useful! I'm open to things like that on branches but likely not on master branch since authentication is the type of thing that can be done so many different ways and is left to many opinions. However if you'd like to implement that on a fork and post back on this issue, I'll create a branch and I could merge it there for future use by anyone wanting to use that specific auth lib with the seed. 👍
