### ISSUE TITLE
How to add Third party(3rd) library

### ISSUE THREAD

**Issue by mshahin364** [NathanWalker/angular-seed-advanced#59]
Could you describe how to add 3rd party library like jquery,bootstrap into the project?

**Comment by vincentpalita** [comment]
@mshahin364 look here: https://github.com/mgechev/angular2-seed/wiki/Add-external-scripts-and-styles

**Comment by NathanWalker** [comment]
Thanks @vincentpalita , indeed since this seed mirrors it's parent, the process is exactly the same 👍

**Comment by mshahin364** [comment]
Thanks @vincentpalita, It's helped me.

**Comment by vincentpalita** [comment]
@mshahin364: Glad it helped you!

**Comment by friksa** [comment]
I followed the steps at https://github.com/mgechev/angular2-seed/wiki/Add-external-scripts-and-styles for jquery.  Did a npm --save install jquery and I can see it installed under node_modules.

The issue is that list/dev/node_modules does not have a copy of jquery.  I even tried npm run build.dev

What else do I need to configure to get jquery into the distribution?

Thanks for a great project!!

**Comment by vincentpalita** [comment]
@friksa : did you add the dependency in the project.config.ts file as mentioned? 

The dist/dev should never contain any node_modules. SystemJS will do the linkings for you in development mode, then when building it will package the files for you from the node_modules folder.

**Comment by friksa** [comment]
Was not sure if someone looked at closed issues, so I created a new one for this.  Thanks!
