### ISSUE TITLE
Am I doing the pull/merge correctly?

### ISSUE THREAD

**Issue by fourctv** [NathanWalker/angular-seed-advanced#68]
I followed the suggestions on forking the seed, by downloading a zip version and configuring upstream/master. Did that a couple weeks ago and started working on my project.

Sed is awesome btw, thanks for the effort.

Then today, I did this to get my project to the latest seed:

> git fetch upstream
> git merge upstream/master

But now I have 100's of conflicts. It looks like the merge did not work as expected, following the suggested workflow!

In other projects I had simply forked it here and then used VSCode `pull` to do the fetch/merge and never had that many conflicts. (I'm also using mgechev's angular2-seed on another project).

So, am I doing something wrong?

Please help...

(ps: is there a gitter or any other chat channel for this seed?)

**Comment by s-f-a-g** [comment]
Hi,
I think the problem is that you forked the project.

1 > create dir my_project (or whatever)
2 > cd my_project
3 > git init
4 > git remote add origin BASED ON YOUR OWN REPO
5 > eventually git pull origin master to retrieve your project
6 > git remote add upstream SEED_PROJECT_URL
7 > git fetch upstream
8 > git merge upstream/master
9 > git add .
10 > git commit -m "Your message"
11 > git push origin master

You now have your own project, on your repository and still able to merge SEED_PROJECT changes.

Hope it helped.

Regards,
Sebastien

**Comment by NathanWalker** [comment]
@fourctv How long has it been since you first downloaded seed?
I assume this is first time you've attempted a fetch and merge?

Usually best to merge upstream master in after downloading and setting up the remotes, this ensures that git is sorted before waiting to merge much later after you've made significant changes.

**Comment by NathanWalker** [comment]
I need to setup a gitter... at moment you can chat me on google chat: walkerrunpdx

**Comment by fourctv** [comment]
@NathanWalker @sebfag I guess I missing the first fetch/merge after downloading seed.

I've made very little changes to the seed itself. I have all my stuff as separate components/files. Most of changes were in package.json & typings.jason to add some 3rd party libraries.

I guess I'll start over, grab a new seed and then move in my stuff.

thanks for the help, closing this now.

**Comment by NathanWalker** [comment]
@fourctv One good thing about the setup is if you do get into `merge hell`, if you had just created a new framework for your codebase and just created new components, it should be easy to download fresh zip and drop the folders of your custom stuff in and away you go. 👍 

Chat me on google if you need help.
