### ISSUE TITLE
Deep Linking

### ISSUE THREAD

**Issue by jovermier** [NathanWalker/angular-seed-advanced#86]
Please add deep linking to this seed as it is not trivial with the framework structure used.

**Comment by NathanWalker** [comment]
Could you please elaborate here?

**Comment by jovermier** [comment]
The top level nav has multiple links (Home, About, etc). Lets say there was a new component called "Top 3 Computer Scientist of All Time" which would be added to the list of nav links. That component (Top 3 CS) has it's own nav (separate from the top level nav) that would link to 3 sub components which would be the profile for each of the top 3 scientists.

Another common example would be a profile settings page where there are multiple sub pages (components) which would allow you to update various profile settings which are grouped by similar content.

**Comment by NathanWalker** [comment]
This should work just fine now with `PathLocationStrategy`?

**Comment by NathanWalker** [comment]
Additionally your question here seems to be more specific to 'how to implement with Angular 2' and for things like that, best to follow the official docs [here](https://angular.io/docs/ts/latest/).

Since the nav will remain the same here and is subject only to modifications made to it's parent seed [angular2-seed](https://github.com/mgechev/angular2-seed) I would recommend adding deep linking to your own project using methods described in Angular's docs or elsewhere. 

If you find the seed is hindering your ability to implement such feature, please reopen.
